#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 21 20:48:31 2021

@author: afifmaulana
#nim: 065002100024
#tugas latihan: latihan praktikum 9
#tanggal: 21 november 2021
"""

a = int(input("masukan angka: "))
b = int(input("masukan pangkatknya: "))

def pangkat(a,b):

    if b >= 1 :
        return a * pangkat(a, b  - 1)

    return a

hasil = pangkat(a, b)
print(f"hasilnya adalah  = {hasil}")
