#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  4 13:15:26 2021

@author: afifmaulana
#nim: 065002100024
#tugas: menerima 2 bilangan
#tanggal: 04 oktober 2021
"""

print("menentukan segitiga")

sisiA = int(input(" sisi 1: "))
sisiB = int(input(" sisi 2: "))
sisiC = int(input(" sisi 2: "))


if(sisiA == sisiB == sisiC):
    print("ini segitiga sama sisi")
    
elif(sisiA == sisiB or sisiA == sisiC or sisiB == sisiC):
    print("ini segitiga sama kaki")
     
elif((sisiA + sisiB <= sisiC) or (sisiA + sisiC <= sisiB) or (sisiA + sisiC <= sisiB)):
    print("ini bukan termasuk segitiga")
    
else:
    print("ini segitiga sembarang")
