#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 29 15:07:56 2021

@author: afifmaulana
#nim: 065002100024
#tugas latihan: realtime 11
#tanggal: 29 november 2021
"""

def bubbleSort(angka):
    n = len(angka)
 
    for i in range(n):
 
        for j in range(0, n-i-1):
 
            if array[j] > array[j+1] :
                array[j], array[j+1] = array[j+1], array[j]
                

                

def binarySearch(array, l, r, x):
 
    if r >= l:
 
        mid = l + (r - l) // 2
 
        if array[mid] == x:
            return mid
 
        elif array[mid] > x:
            return binarySearch(array, l, mid-1, x)
 
        else:
            return binarySearch(array, mid + 1, r, x)
 
    else:
        return -1
    

array = [ 0, 13,22, 38, 44, 50, 66, 71, 89, 90, 103, 111 ]


x = input("masukan list yang ingin di coba: ")
x = int(x)

bubbleSort(array)

result = binarySearch(array, 0, len(array)-1, x)
result = int(result)
print("Diurutkan menjadi:", array)


if result != -1:
    print("terdapat indeks ", (result)+1)
else:
    print("tidak ada indeks")
