#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 15 14:50:58 2021

@author: afifmaulana
#nim: 065002100024
#tugas latihan: realtime 9
#tanggal: 15 november november 2021
"""

def rekursif(angka = 0, jumlah = 0, n = 1):
    if (jumlah <= 0):
        return 0
    else:
        angka = int(input("Masukkan bilangan ke-" + str(n) + ": "))
        if(jumlah == 1):
            return angka
        else:
            n+=1
            return angka + rekursif(angka, jumlah -1, n)

jumlah = int(input("Masukkan angka: "))
nilai  = rekursif (jumlah = jumlah)
print("Hasil penjumlahan tersebut adalah: " + str(nilai))
