#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 15 14:50:58 2021

@author: afifmaulana
#nim: 065002100024
#tugas latihan: realtime 9
#tanggal: 15 november november 2021
"""

def penjumlahan(angka = 0, jmlh = 0, n = 1):
    if (jmlh <= 0):
        return 0
    else:
        angka = int(input("Masukkan bilangan ke-" + str(n) + ": "))
        if(jmlh == 1):
            return angka
        else:
            n+=1
            return angka + penjumlahan(angka, jmlh-1, n)

jumlah = int(input("Masukkan angka: "))
nilai  = penjumlahan(jmlh = jumlah)
print("Hasil penjumlahan tersebut adalah: " + str(nilai))
